from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional


# --- Search related data classes ---


@dataclass
class SearchFilters:
    """Filters that LLM0 can request for Bing search."""
    include: List[str] = field(default_factory=list)
    exclude: List[str] = field(default_factory=list)
    allow_domains: List[str] = field(default_factory=list)
    deny_domains: List[str] = field(default_factory=list)


@dataclass
class SearchRequest:
    """
    One web search configuration.

    `when` is passed through to the search backend and typically supports:
    - "day"   : last 24 hours
    - "week"  : last 7 days (use cautiously, not as default)
    - "month" : last ~30 days
    - "year"  : last ~12 months
    - "any"   : no time filter
    """
    query: str
    when: str = "week"
    filters: SearchFilters = field(default_factory=SearchFilters)
    max_results: int = 20


@dataclass
class SearchResult:
    """One search result row coming from BingSift."""
    id: str             # internal ID used inside DeepSeeker, e.g. "r1"
    title: str
    url: str
    snippet: str
    domain: Optional[str] = None
    display_url: Optional[str] = None
    guessed_time: Optional[str] = None
    attribution: Optional[str] = None


@dataclass
class ArticleSummary:
    """Summary of one article produced by LLM1."""
    result_id: str
    url: str
    title: str
    summary: str
    key_points: List[str] = field(default_factory=list)
    relevance_score: float = 0.0
    notes: Optional[str] = None


# --- LLM0 protocol actions ---


@dataclass
class PlanDecision:
    """
    LLM0's high-level plan.

    - When action == "direct_answer", `direct_answer` must be filled.
    - When action == "search_then_answer", there must be at least one SearchRequest
      in `search_requests`.
    """
    action: str  # "direct_answer" or "search_then_answer"
    direct_answer: Optional[str] = None
    search_requests: List[SearchRequest] = field(default_factory=list)
    notes: Optional[str] = None


@dataclass
class SelectionDecision:
    """Decision of which search results should be read by LLM1."""
    selected_ids: List[str]
    notes: Optional[str] = None


@dataclass
class FinalAnswer:
    """Final report generated by LLM0."""
    answer: str
    key_points: List[str] = field(default_factory=list)
    used_results: List[str] = field(default_factory=list)  # list of result_ids
    notes: Optional[str] = None


# --- Logging / steps ---


@dataclass
class StepEvent:
    """One step in the orchestration pipeline."""
    step_type: str  # e.g. "search", "plan", "select", "summarize", "final"
    message: str
    data: Dict[str, Any] = field(default_factory=dict)
    error: bool = False


@dataclass
class DeepSeekerReport:
    """What the orchestrator returns for one user query."""
    question: str
    steps: List[StepEvent]
    final_answer: Optional[FinalAnswer] = None
    raw_summaries: List[ArticleSummary] = field(default_factory=list)
    search_results: List[SearchResult] = field(default_factory=list)
